### ISSUE TITLE
Ask about the usage of the "clusters" parameter

### ISSUE THREAD

**Issue by b-niu** [gerstung-lab/MutationTimeR#6]
```
clusters <- data.frame(cluster= , n_ssms=, proportion=) 
# Optional data.frame with subclonal cluster locations (VAF proportion) and size (number of variants n_ssms)
```

Dear author, I noticed this optional input.
Can you explain what "n_ssms" and "proportion" mean?
Is "cluster" a column of "cluster IDs"?

Thanks!

**Comment by alhafidzhamdan** [comment]
Hi there,

Perhaps relating to this, how does one generate that cluster data? I can't seem to find guidance on this.
Thank you!

**Comment by carladosanjos** [comment]
Dear author,

Just want to let you know that it is a great tool and would be awesome if more people could use it. 

I am having difficulties to compare the templates to the real world data output, so I wish to know which program did you use to get the "clusters" output. It will help in order to answer the following questions:

What is the "n_ssms" field in the cluster object? I cannot find what "n_ssms" means anyware. 
Why the cluster object has 3 header and 4 columns? 
What is the data that corresponds to each column?

Many thanks for your help!

Best wishes
Have you

**Comment by carladosanjos** [comment]
> ```
> clusters <- data.frame(cluster= , n_ssms=, proportion=) 
> # Optional data.frame with subclonal cluster locations (VAF proportion) and size (number of variants n_ssms)
> ```
> 
> 
> Dear author, I noticed this optional input.
> 
> Can you explain what "n_ssms" and "proportion" mean?
> 
> Is "cluster" a column of "cluster IDs"?
> 
> 
> Thanks!

Did you find an answer for that?

**Comment by mg14** [comment]
`cluster` is the index of subclonal clusters. The index `1` denotes the clonal cluster, otherwise `cluster=1,2,...`
`n_ssms` represents the number of Simple Somatic Mutations per subclonal cluster. If there are no subclonal clusters, then `n_ssms = nrow(vcf)`. Only the relative value matters.
`proportion` denotes the cellular proportion of the subclonal cluster. For the clonal cluster this is the tumour purity. All subclonal clusters have proportion < purity. Note that purity should be consistent with the `clonal_frequency` column of the corresponding `GRanges` object `cn` storing the copy number data. Subclonal clusters with proportion close to purity can be difficult to separate from the clonal cluster and confound the timing. 

The default argument is that only clonal mutations are present. A variety of tools exist to detect clusters of subclonal mutations, e.g. https://github.com/PCAWG-11/Heterogeneity. 

In the absence of detailed subclonal cluster information, it may be worth introducing a placeholde for subclonal mutations at 50% purity using 

```
clusters < - data.frame(cluster=1:2, 
                        proportion=max(cn$clonal_frequency,na.rm=TRUE) * c(1, 0.5), ## enabling subclonal mutations at approx. 50% purity
                        n_ssms=c(90,10)) ## assuming a prior expectation of 10% subclonal mutationss
```
